# Generated by Django 5.2.7 on 2025-10-21 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField(db_index=True)),
                ('gols_mandante', models.IntegerField(blank=True, null=True)),
                ('gols_visitante', models.IntegerField(blank=True, null=True)),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_mandante', to='campeonato.time')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_visitante', to='campeonato.time')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mandante', 'visitante'), name='partida_unica')],
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField()),
                ('pontos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('gols_marcados', models.IntegerField(default=0)),
                ('gols_sofridos', models.IntegerField(default=0)),
                ('saldo_gols', models.IntegerField(default=0)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='campeonato.time')),
            ],
            options={
                'ordering': ['rodada', '-pontos', '-vitorias', '-saldo_gols', '-gols_marcados', 'time__nome'],
                'constraints': [models.UniqueConstraint(fields=('time', 'rodada'), name='classificacao_unica_por_rodada')],
            },
        ),
    ]
