# Generated by Django 5.2.7 on 2025-10-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacao',
            options={'ordering': ['rodada', '-pontos', '-vitorias', '-saldo_gols', '-gols_marcados', 'cartoes_vermelhos', 'cartoes_amarelos', 'time__nome']},
        ),
        migrations.AddField(
            model_name='classificacao',
            name='cartoes_amarelos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='cartoes_vermelhos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='cartoes_amarelos_mandante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='cartoes_amarelos_visitante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='cartoes_vermelhos_mandante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='cartoes_vermelhos_visitante',
            field=models.IntegerField(default=0),
        ),
    ]
